# Change baseurl before deploy
baseurl = "https://blog.5-23.dev"
languageCode = "en-us"
paginate = 5
title = "rustacean@5-23.dev"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "ko"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

# Change it to your Disqus shortname before using
# disqusShortname = "hugo-theme-stack"
theme = "hugo-theme-stack"
enableRobotsTXT = true